<a href="https://colab.research.google.com/github/kairamilanifitria/Bootcamp-NLP/blob/main/26082024_2_ANN_training_with_dummy_datasets_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2 ANN training with dummy datasets

Syllabus:
1. create a linear function for the dummy datasets
2. create dummy datasets
3. create model
4. create training scheme
5. create inference function

## 1. create a linear function for the dummy datasets

for this tutorial we are gonna make this function for the datasets,
f(x1,x2,x3,x4) = x1*w1+x2*w2+x3*w3+x4*w4
w1 = 1
w2 = 2
w3 = 3
w4 = 4

In [ ]:
def function(x1, x2, x3, x4):
  w1,w2,w3,w4 = 1,2,3,4
  return  x1*w1+x2*w2+x3*w3+x4*w4

In [ ]:
#example
x1,x2,x3,x4 = 1,2,3,4
function(x1,x2,x3,x4) #1+4+9+16=30

30

## 2. create dummy datasets


In [ ]:
import numpy as np

In [ ]:
def create_dummy_datasets(n=1000):
  x = np.random.randint(0, 2000, size=(n,4))

  y = []
  for i in x:
    y_temp = function(*i) #i[0], i[1], ..., i[n-1] n: panjang arraynya
    y.append(y_temp)

  y = np.asarray(y)

  return x,y

In [ ]:
N_SAMPLE = 1000
data = create_dummy_datasets(N_SAMPLE)

In [ ]:
print(data[0]) #for the x data
print(data[1]) #for the y data

[[ 905   16 1898 1332]
 [ 951 1190 1772 1118]
 [ 133 1652  910 1969]
 ...
 [1640  789 1789  717]
 [1843  161  922 1861]
 [1780  743  420   18]]
[11959 13119 14043  9443  7343 12646  9965  4729  5321 13180  7919  2999
 14690 11884 10367  8816 14598  4934  9894 11901  6005  7129  3457 10996
  9870  8025  7773  8819 13693  6219  9568 12045  8226  5760  9360  9225
 10291 12858 12675  7113  7394 14315 13951  7214 14145 12403  7314  7169
  7764 12092 12116 13511 10102  7855  7841 13097  9231  6713  9236 10807
 13192 12869 12350 11868  9440 10687  8578 14308  9189  5974  8680  5873
  8077 10688 11453 13390  7715 11380 10657 13453 12987 11335 12861  6351
  6610 12665  7959  6381  9441  7587  8952  8855 16172 10465  9193  6209
 11909 13806  7962  5023  6178 11989  9927 10094 15573 12703 12145 13982
  4219  7029 14166 13366  4040  9342  8621  3310 10965  6859 13569 14603
 10915  4654  8875  4419  7603  8898  4899 10988  7533  6392 11018 11855
 10518 12182  8666 11703 10576 14719  8830  7377  528

In [ ]:
#lets convert it to torch.tensor dtype torch.float32 so it can run smoothly on neural nets
import torch

In [ ]:
X = torch.tensor(data[0], dtype = torch.float32)
y = torch.tensor(data[1], dtype = torch.float32)

In [ ]:
print(X)
print(y)

tensor([[ 905.,   16., 1898., 1332.],
        [ 951., 1190., 1772., 1118.],
        [ 133., 1652.,  910., 1969.],
        ...,
        [1640.,  789., 1789.,  717.],
        [1843.,  161.,  922., 1861.],
        [1780.,  743.,  420.,   18.]])
tensor([11959., 13119., 14043.,  9443.,  7343., 12646.,  9965.,  4729.,  5321.,
        13180.,  7919.,  2999., 14690., 11884., 10367.,  8816., 14598.,  4934.,
         9894., 11901.,  6005.,  7129.,  3457., 10996.,  9870.,  8025.,  7773.,
         8819., 13693.,  6219.,  9568., 12045.,  8226.,  5760.,  9360.,  9225.,
        10291., 12858., 12675.,  7113.,  7394., 14315., 13951.,  7214., 14145.,
        12403.,  7314.,  7169.,  7764., 12092., 12116., 13511., 10102.,  7855.,
         7841., 13097.,  9231.,  6713.,  9236., 10807., 13192., 12869., 12350.,
        11868.,  9440., 10687.,  8578., 14308.,  9189.,  5974.,  8680.,  5873.,
         8077., 10688., 11453., 13390.,  7715., 11380., 10657., 13453., 12987.,
        11335., 12861.,  6351.,  6610.

## 3.lets build a model

In [ ]:
from torch import nn

In [ ]:
class RegressionModel(nn.Module):
  def __init__(self, input_node=4, output_node=1):
    super().__init__()
    self.input_node = input_node
    self.output_node = output_node

    self.fc = nn.Linear(self.input_node, self.output_node, bias=False) #we want to make the bias false so it can relate with the function but in most cases you need the bias to be true

  def forward(self,x):
    return self.fc(x)

## 4. Let's Create training scheme
before that let's understand about concept of optimization and loss function

In [ ]:
sample_model = RegressionModel()
optim = torch.optim.SGD(sample_model.parameters(), lr=0.001) #Stochastic Gradient Descent
loss_fn = nn.MSELoss() #Mean Squared error loss

In [ ]:
sample_X = X
sample_y = y

BATCH_SIZE = 10
sample_X = torch.reshape(sample_X, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4)) #let's make batch 10 | (N_SAMPLE,4) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4) -> (100, 10, 4)
sample_y = torch.reshape(sample_y, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1)) #let's make batch 10 | (N_SAMPLE,1) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1) -> (100, 10, 1)

# scale data
sample_X = sample_X/2000
sample_y = sample_y/2000

In [ ]:
print(sample_X.shape)
print(sample_y.shape)
print(sample_model)

torch.Size([100, 10, 4])
torch.Size([100, 10, 1])
RegressionModel(
  (fc): Linear(in_features=4, out_features=1, bias=False)
)


In [ ]:
#this is what we call one epoch training
for i in range(1000):
  print("EPOCH ", i)
  for i, (inputs, target) in enumerate(zip(sample_X, sample_y)):
    output = sample_model(inputs)
    loss = loss_fn(output,target)
    if i % 10 == 0:
      print("   step ",i)
      print(loss.item())
    # Backpropagation
    optim.zero_grad() # clear previous gradient
    loss.backward() # calculate gradient
    optim.step()

Streaming output truncated to the last 5000 lines.
   step  90
4.1899794744892915e-09
EPOCH  762
   step  0
7.487381381565683e-09
   step  10
5.913130873835826e-09
   step  20
3.6155654026259754e-09
   step  30
4.181907709011057e-09
   step  40
4.390165120327083e-09
   step  50
2.293239820261306e-09
   step  60
3.3216622785658956e-09
   step  70
2.249312514024382e-09
   step  80
3.0132354389422744e-09
   step  90
4.1953169827024794e-09
EPOCH  763
   step  0
7.485619235580998e-09
   step  10
5.914341905111087e-09
   step  20
3.6069196518440094e-09
   step  30
4.16128509428404e-09
   step  40
4.376766948865907e-09
   step  50
2.2945882971470155e-09
   step  60
3.3082812045392984e-09
   step  70
2.2449486714037903e-09
   step  80
3.01434388561006e-09
   step  90
4.178548174138541e-09
EPOCH  764
   step  0
7.459749262750393e-09
   step  10
5.91258508819692e-09
   step  20
3.5834772926790492e-09
   step  30
4.164286249164206e-09
   step  40
4.359350214144797e-09
   step  50
2.28856866790749

In [ ]:
#lets see the total loss
loss_total = []
for inputs, target in zip(sample_X, sample_y):
  output = sample_model(inputs)
  loss = loss_fn(output,target)
  loss_total.append(loss.item())

loss_average = np.mean(loss_total)

In [ ]:
print(loss_average)

3.914661297343969e-09


In [ ]:
#lets we see the parameters, that's the weight that we trained
for param in sample_model.parameters():
  print(param.data)

tensor([[1.0001, 2.0001, 3.0000, 3.9998]])


## 5. create inference function

In [ ]:
def inference(x1,x2,x3,x4):
  inputs = torch.tensor([[x1,x2,x3,x4]], dtype=torch.float32)
  inputs = inputs/2000
  output = sample_model(inputs)
  output*=2000

  return output[0].detach().numpy()

def function(x1, x2, x3, x4):

w1,w2,w3,w4=1,2,3,4

return x1*w1+x2*w2+x3*w3+x4*w4

In [ ]:
x1,x2,x3,x4 = 3,4,5,6
inference(x1,x2,x3,x4), function(x1,x2,x3,x4) # compare prediksi vs fungsi asli data

(array([49.999397], dtype=float32), 50)